- src/spaceone/monitoring/api/plugin/data_source.py
- src/spaceone/monitoring/api/plugin/metric.py
- src/spaceone/monitoring/connector/aws_boto_connector/__init__.py
- src/spaceone/monitoring/info/__init__.py
- src/spaceone/monitoring/info/common_info.py
- src/spaceone/monitoring/info/metric_info.py
- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/manager/data_source_manager.py
- src/spaceone/monitoring/model/data_source_response_model.py
- src/spaceone/monitoring/service/data_source_service.py
- src/spaceone/monitoring/service/metric_service.py
- test/api/test_data_source_api.py
- test/api/test_metric_api.py
- test/connector/test_aws_boto_connector.py
- test/manager/test_aws_manager.py
- test/service/test_data_source_service.py
- test/service/test_metric_service.py
modify unary to unary Metrics class
> add init method in DataSource

- src/spaceone/monitoring/model/data_source_response_model.py
> Change format for requirement

- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
> set region_name on secret

- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
Update for debugging for cloud_watch
> Update for debugging for cloud_watch

- src/spaceone/monitoring/manager/aws_manager.py
Added new print for list of metrics
> Added new print for list of metrics

- src/spaceone/monitoring/manager/aws_manager.py
Add region if region_name is not available in resource or secret_data
> Add region if region_name is not available in resource or secret_data

- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
- Remove unnecessary print & pprint
> Update for removing print or pprint

- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
Update to removing print & pprint
> Update to removing print & pprint

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
Update for multi processing within aws
> Update for multi processing within aws

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
Update for case of single/plural
> Update for case of single/plural

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
docs: update README.md
docs: add pull request template
> docs: update README.md

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/manager/aws_manager.py
feat: add Cloudwatch Agent Namespace (CWAgent)
Support namespace 'CWAgent' for cloudwatch agent monitoring (#47)
> feat: add Cloudwatch Agent Namespace (CWAgent)

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
refactor: update metric list get_data
> refactor: update metric list get_data

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/manager/aws_manager.py
> etc: add log for debug

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/manager/aws_manager.py
fix: modify region_code -> region_name
> fix: modify region_code -> region_name

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/info/metric_info.py
- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/manager/metric_manager.py
- src/spaceone/monitoring/model/metric_response_model.py
- src/spaceone/monitoring/service/metric_service.py
refactor: metric
Refactoring Cloudwatch Plugin (#54)
> refactor: metric

- src/spaceone/monitoring/model/data_source_response_model.py
refactor: remove supported_resource_type
Refactoring Cloudwatch Plugin (#54)
> refactor: remove supported_resource_type

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
> refactor: modify metric_key

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/info/metric_info.py
- src/spaceone/monitoring/manager/aws_manager.py
- src/spaceone/monitoring/service/metric_service.py
- test/api/test_metric_api.py
refactor: modify get_metric_data
> refactor: modify get_metric_data

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
feat: add group
Refactoring Cloudwatch Plugin (#54)
> feat: add group

- src/spaceone/monitoring/connector/aws_boto_connector/cloud_watch.py
- src/spaceone/monitoring/manager/aws_manager.py
fix: modify 'global' region for client session
> fix: modify 'global' region for client session
